spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update # TODO: Introduce migrations and set this value to 'validate'
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

google:
  books:
    enabled: false
    key: SECRET
