spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: update # TODO: Introduce migrations and set this value to 'validate'
    open-in-view: false

google:
  books:
    enabled: false
    url: https://www.googleapis.com/books/v1/volumes
    key: SECRET
